name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: checkout code
        uses: actions/checkout@v2
      - name: golangci-lint
        if: matrix.os != 'windows-latest'
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36
      - name: go test
        run: |
          go version
          go env
          go test -cover -coverprofile coverage.txt -race -v ./...
      - uses: codecov/codecov-action@v1
